### ISSUE TITLE
Quantify asymmetry

### ISSUE THREAD

**Issue by sedrubal** [uoaerg/draft-jones-transport-for-satellite#17]
In "2.1 Geosynchronous Earth Orbit (GEO)" it is written:

> Links can be highly asymmetric in terms of capacity, the one-way delay and their cost of operation.

I'm interested in numbers at this point. What are typical available data rates, one-way delays and costs of operation? Are one-way delays really asymmetric?

**Comment by davidfdzp** [comment]
Links can be asymmetric also for LEO systems, like in a factor of 1:10. Typical bandwidths in the order or Mbit/s can be assumed nowadays, but exact amount depends on the provider. There can be delay asymmetry too, due to the return link being a shared medium with random access (collisions, retransmissions) or resources reservation required (extra RTT at least for resources request and assignment protocol).

**Comment by adventureloop** [comment]
Appendix A contains example profiles, which can be used to calculate the asymmetry for each described link. I think this is the best we can offer right now, until there is another doc that we can cite

**Comment by adventureloop** [comment]
I will add a pointer to the appendix for now. I agree we should have numbers, but I need to figure out how to include them in the main text
